### ISSUE TITLE
Evaluating log probability with Categorical observations

### ISSUE THREAD

**Issue by zashwood** [slinderman/ssm#14]
Firstly, than you very much for your code base - it is really nice to use.
`assert(data.dtype == int or data.dtype == bool)` (line 393 of observations.py) throws an error when the Simple HMM notebook is altered to change the observations to "categorical" and when evaluating the log probability i.e. when running
`true_hmm = HMM(5, 3, observations="categorical")`
`z, y = true_hmm.sample(1000)`
`true_ll = true_hmm.log_probability(y)`
This is due to `data = np.zeros((T+1, D))` (line 73 of core.py), which instantiates data as a numpy array of float 64s.

**Comment by slinderman** [comment]
Good catch! I've added a `dtype` property for the HMM _Observations objects, changed the sampling code to use the proper data type, and added a type check to the function wrappers.  See https://github.com/slinderman/ssm/commit/65a0e8af22b82709a4801ae1a9cdd954a7048e78I still need to think about the proper way to do this for SLDS, but for now the SLDS sampling code works since the emissions are sampled in one step rather than iteratively.  In the future I'd like to change this to allow for "recurrent" dependencies between emissions and latent states in the SLDS as well, but I'll cross that bridge when the time comes.
