### ISSUE TITLE
Feature request: Convergence detection

### ISSUE THREAD

**Issue by kharris** [slinderman/ssm#30]
I also would like some version of "detecting convergence"... in other words, has the ELBO stabilized. The reason is that I am comparing run-times with another algorithm that has a convergence condition, and to be fair to your algorithm code I'll have to fine-tune the number of iterations for every problem set. 

This may be close to a duplicate of "early stopping", but I do not need it to be a function of any test set.

P.S. got the code running!

**Comment by slinderman** [comment]
Thanks Kam, you're not the first to ask for this.  I just added a simple tolerance argument to the EM code.  See https://github.com/slinderman/ssm/commit/38417e5fd33a5926943205b4d49340f31199d7e3. It seems not so trivial to do this in a general way, because the scale of the likelihood differs from problem to problem.  As a simple solution, I'll just leave it up to the user.  

In the future, I'd like to let the user specify custom stopping criteria.  There's another issue open for this already, so I'll track it there and close this one.
