### ISSUE TITLE
Is it possible to fit states to more than one series at a time?

### ISSUE THREAD

**Issue by ewerlopes** [slinderman/ssm#37]
Hi,

Thanks for sharing this library. I was wondering whether we can fit the states on a collection of time series instead of just one as you do on the examples.

Thanks.

**Comment by bagibence** [comment]
Yes, I've been using SLDS on a list of recordings. You just have to pass a list of time series instead of a single one to the functions. The list elements have to be in the shape of `T x D` where T is the number of time points (the different time series can have different lengths) and D is the dimensionality of your observations.

**Comment by slinderman** [comment]
Thanks @bagibence, that's exactly right.

**Comment by ewerlopes** [comment]
@bagibence That is good news! I am going to try it right now! Thanks for the prompt reply!

**Comment by ewerlopes** [comment]
@slinderman, just one doubt... the fact that we see the ELBO not having a monotonically increasing behavior comes from the fact you are using the stochastic version for the mean field variational inference, right?

**Comment by slinderman** [comment]
The ELBO should monotonically increase for HMMs fit with EM.  We've implemented exact M-steps for most observation models.  For SLDS, the examples are currently using black box variational inference with SGD, Adam, rmsprop, etc.  We've implemented a few variational families including mean field, and a structured variational posterior
