### ISSUE TITLE
Initialization of autoregressive observations not consistent with model

### ISSUE THREAD

**Issue by themattinthehatt** [slinderman/ssm#92]
I've been playing around with new initializations for ARHMMs and noticed an issue with how these are initialized here:
https://github.com/slinderman/ssm/blob/c2814bcd928b666ae365d25ebb6e9784ce9c3389/ssm/observations.py#L863

For a given time point `t` that is identified with state `k` (when `localize=True`), the linear regression should match up `x_t` with `x_{t-1}, ..., x_{t-lags}` to find the parameters for state `k`.

However, the data that is actually being matched up is `x_{t+lags}` with `x_t, ..., x_{t+lags-1}`, which is inconsistent with the m step performed in https://github.com/slinderman/ssm/blob/c2814bcd928b666ae365d25ebb6e9784ce9c3389/ssm/observations.py#L895

A proposed solution for `AutoRegressiveObservations.initialize()` would be:
```
@ensure_args_are_lists
    def initialize(self, datas, inputs=None, masks=None, tags=None, localize=True):
        from sklearn.linear_model import LinearRegression

        # Sample time bins for each discrete state
        # Use the data to cluster the time bins if specified.
        Ts = [data.shape[0] for data in datas]
        if localize:
            from sklearn.cluster import KMeans
            km = KMeans(self.K)
            km.fit(np.vstack(datas))
            zs = np.split(km.labels_, np.cumsum(Ts)[:-1])
            zs = [z[self.lags:] for z in zs] # == UPDATED ==
        else:
            zs = [npr.choice(self.K, size=T-self.lags) for T in Ts]

        ...
```

**Comment by slinderman** [comment]
Good catch! Looks like we're still initializing `As` so that `(x_{t-lags}, ... x_{t-1}) predicts `x_t`, but the time indices `t` that we choose are off by `lags` from those that KMeans chooses.  If `lags` is big, that could have a pretty big effect, but I bet for my cases where I typically have `lags <= 3` it's not a huge deal.  Have you noticed an effect from the fixed initialization?  

Fix pushed in https://github.com/slinderman/ssm/commit/4bb518f559c346dcc11ffe38b65ebd60d09e0988.

Thanks again @themattinthehatt!
